(() => {
  const C = window.CLINICAL_DATA;
  if (!C) return;

  Object.assign(C.sources, {
    ais2026: {name:'2026 AHA/ASA Guideline for the Early Management of Acute Ischemic Stroke',year:'2026',org:'AHA/ASA',url:'https://professional.heart.org/en/science-news/2026-guideline-for-the-early-management-of-patients-with-acute-ischemic-stroke',note:'用于卒中系统、静脉溶栓与机械取栓路径；本站不简化复杂禁忌证。'},
    ich2022: {name:'2022 AHA/ASA Guideline for Spontaneous Intracerebral Hemorrhage',year:'2022',org:'AHA/ASA',url:'https://professional.heart.org/en/science-news/2022-guideline-for-the-management-of-patients-with-spontaneous-intracerebral-hemorrhage'},
    aorta2022: {name:'2022 ACC/AHA Guideline for the Diagnosis and Management of Aortic Disease',year:'2022',org:'ACC/AHA',url:'https://professional.heart.org/en/science-news/2022-guideline-for-the-diagnosis-and-management-of-aortic-disease',note:'急性主动脉综合征药物目标与手术/腔内策略需结合病型和专科中心流程。'},
    dka2024: {name:'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report',year:'2024',org:'ADA/EASD/JBDS/AACE/DTS',url:'https://diabetesjournals.org/care/article/47/8/1257/156808/Hyperglycemic-Crises-in-Adults-With-Diabetes-A'},
    rcukElectrolyte2025: {name:'RCUK 2025 Special Circumstances — Hyperkalaemia',year:'2025',org:'Resuscitation Council UK',url:'https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/special-circumstances-guidelines'},
    rcukDrowning2025: {name:'RCUK 2025 Special Circumstances — Drowning',year:'2025',org:'Resuscitation Council UK',url:'https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/special-circumstances-guidelines'},
    rcukHeat2025: {name:'RCUK 2025 Special Circumstances — Hyperthermia',year:'2025',org:'Resuscitation Council UK',url:'https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines/special-circumstances-guidelines'},
    acgUGIB2021: {name:'ACG Clinical Guideline: Upper Gastrointestinal and Ulcer Bleeding',year:'2021',org:'American College of Gastroenterology',url:'https://pubmed.ncbi.nlm.nih.gov/33929377/'}
  });

  Object.assign(C.topics, {
    '急性缺血性卒中': {status:'verified-partial',sourceIds:['ais2026'],summary:'疑似急性缺血性卒中应立即启动卒中流程，记录最后正常时间/症状发现时间，快速排除低血糖并完成脑影像；治疗机会与时间高度相关。',redFlags:['新发偏瘫/偏身麻木','新发失语或构音障碍','凝视偏斜或视野缺损','突发严重共济失调/脑干症状','意识水平下降'],steps:['立即记录最后正常时间、发病/发现时间、抗凝药使用和既往功能状态，床旁血糖并进行标准化神经功能评估。','尽快完成非增强头颅 CT 或等效卒中影像以排除脑出血；疑似大血管闭塞时按卒中系统尽快完成血管影像。','2026 AHA/ASA 更新支持在符合条件患者中扩大 4.5 小时内替奈普酶的使用；本站不把复杂溶栓适应证、禁忌证和剂量简化成单一按钮。','大血管闭塞患者的机械取栓适应证较旧版进一步扩大；部分大梗死核心患者仍可获益。基底动脉闭塞、发病 24 小时内且 NIHSS≥10 的合适患者有强推荐的 EVT 证据。','转运目的地应结合本地卒中系统和转院效率；必要时直接转至可行 EVT 的中心，避免可避免的二次延误。'],caution:'不要因“症状较轻”自行排除致残性卒中；不要因准备 CTA/高级影像而无故延误明确适合的再灌注治疗。血压、溶栓药物与抗栓方案需进入专门卒中路径。'},
    '自发性脑出血': {status:'verified',sourceIds:['ich2022'],summary:'脑出血是时间敏感的神经急症。核心任务是快速影像确认、平稳控制血压、立即识别并逆转抗凝、监测神经恶化，并尽早进入神经重症/神经外科系统。',redFlags:['突发局灶神经功能缺损伴头痛/呕吐','进行性意识障碍','抗凝治疗背景','快速神经恶化','脑疝征象或脑积水风险'],steps:['立即完成头颅非增强 CT；结合发病时间、抗栓药物和影像特征评估血肿扩大的风险。','轻至中度 ICH 的急性降压应追求平稳、持续并减少血压波动，避免大幅反复波动。','抗凝相关 ICH 应立即停用并按药物类型逆转：华法林路径使用 PCC 并纠正维生素 K；达比加群有 idarucizumab；Xa 抑制剂可用 andexanet alfa 等专门逆转策略。','尽快转入具备神经重症和神经外科能力的卒中中心；出现脑积水、后颅窝病变或神经恶化时尤其需要紧急升级。','无癫痫证据时不常规预防性使用抗癫痫药；常规预防性糖皮质激素和持续高渗治疗不能改善结局。'],caution:'血小板输注并非所有抗血小板相关 ICH 都有益；除紧急手术或严重血小板减少等特定情形外，盲目输注可能有害。'},
    '急性主动脉综合征': {status:'source-bound',sourceIds:['aorta2022'],summary:'突发胸背痛伴灌注异常、脉搏/血压不对称或新发主动脉瓣返流时应高度警惕急性主动脉综合征，立即进行抗冲击治疗、确定解剖分型并联系主动脉中心。',redFlags:['突发撕裂样/爆发性胸背痛','脉搏缺失或双侧血压明显不对称','新发主动脉瓣返流杂音','晕厥、卒中样症状或肢体/肠系膜缺血','休克/心包压塞'],steps:['快速 ABC 评估、双上肢血压与脉搏检查；在可行条件下尽快完成 CTA，必要时选择 TEE/MRI。','立即开始镇痛和抗冲击（anti-impulse）治疗，通常先控制心率/剪切力，再按灌注情况控制血压；具体靶值和药物由专门流程决定。','Stanford A 型夹层属于外科急症；临床稳定者应考虑转至高容量、经验丰富的主动脉中心。','B 型夹层的治疗取决于是否存在破裂、进行性扩张、持续疼痛、难控高血压或器官灌注不良等并发症。'],caution:'在未排除主动脉夹层前，不应机械套用 ACS 抗栓/溶栓路径。本站暂不硬编码通用 HR/SBP 靶值，以免忽略休克、器官灌注和病型差异。'},
    'DKA/HHS': {status:'verified',sourceIds:['dka2024'],summary:'成人 DKA/HHS 的治疗核心是液体、胰岛素、电解质监测/补充和诱因处理；开始胰岛素前必须先确认钾水平，治疗过程中持续监测血糖、钾、酸碱和渗透压。',redFlags:['意识改变或休克','严重脱水','K<3.5 mmol/L','严重酸中毒/合并重症感染','HHS 高渗状态或 DKA/HHS 混合'],steps:['确认血糖、血酮（优先 β-羟丁酸）、电解质、肾功能和静脉血气；HHS 需动态监测血清渗透压，同时寻找感染、漏打胰岛素、心肌缺血等诱因。','DKA 常用短效胰岛素静脉固定速率 0.1 U/kg/h；血糖降至 <13.9 mmol/L（250 mg/dL）后加入 5%–10% 葡萄糖，并将胰岛素降至约 0.05 U/kg/h，继续至酮症酸中毒真正缓解。','无明显酸中毒的 HHS 可从 0.05 U/kg/h 固定速率静脉胰岛素开始；若存在显著酮症/酸中毒则按混合 DKA/HHS 使用 0.1 U/kg/h。','血钾降至 <5.0 mmol/L 后通常开始补钾，目标维持约 4–5 mmol/L；K<3.5 mmol/L 时先补钾并延迟胰岛素，直到 K>3.5 mmol/L。','治疗中血糖每 1–2 小时监测；电解质、肾功能、β-羟丁酸和静脉 pH 通常每 4 小时复查，HHS 同时监测渗透压。'],doses:['DKA：短效胰岛素 IV 0.1 U/kg/h。','无酸中毒 HHS：短效胰岛素 IV 0.05 U/kg/h。','多数 DKA 患者补钾常用 20–30 mmol/L 加入静脉液体；K<3.5 mmol/L 时可先以约 10 mmol/h 补钾并暂停胰岛素。'],target:'DKA 缓解：血酮 <0.6 mmol/L 且静脉 pH≥7.3 或 HCO₃⁻≥18 mmol/L；不应仅依赖阴离子间隙。HHS 缓解应结合渗透压 <300 mOsm/kg、认知改善、尿量及血糖等综合判断。',caution:'老年、心衰、肾衰患者液体速度必须个体化；补液与胰岛素可快速降低血钾，严密监测是核心安全措施。'},
    '高钾血症': {status:'verified',sourceIds:['rcukElectrolyte2025'],summary:'中重度高钾应同步处理三件事：稳定心肌、把钾移入细胞、从体内清除钾，并持续 ECG/血钾/血糖复评。',redFlags:['K>6.5 mmol/L','高钾相关 ECG 改变','进行性肌无力/心动过缓','肾衰或透析患者','心搏骤停'],steps:['中度（6.0–6.4）和重度（>6.5 mmol/L）高钾：给予短效胰岛素 10 U + 葡萄糖 25 g IV，把钾移入细胞；治疗后严密监测低血糖。','可雾化沙丁胺醇 10–20 mg 作为胰岛素-葡萄糖的辅助治疗，不应单独依赖。','严重高钾伴 ECG 改变：10% 氯化钙 10 mL IV 约 5 分钟；若无氯化钙，可用 10% 葡萄糖酸钙 30 mL 约 10 分钟。','难治性重度高钾应尽快联系肾脏/重症团队并考虑透析；同时寻找肾衰、药物、酸中毒、组织破坏等原因。','高钾性心搏骤停按标准 ALS，同时给予 10% 氯化钙 10 mL IV 和碳酸氢钠 50 mmol IV；分开通路或充分冲管。'],doses:['短效胰岛素 10 U + 葡萄糖 25 g IV。','雾化沙丁胺醇 10–20 mg（辅助）。','ECG 改变：10% 氯化钙 10 mL IV/5 min；或 10% 葡萄糖酸钙 30 mL IV/10 min。'],caution:'钙剂不降低血钾，只用于心肌膜稳定；必须同时启动降钾/移钾治疗并监测血糖。'},
    '热射病': {status:'verified',sourceIds:['rcukHeat2025'],summary:'热射病是高热伴中枢神经功能异常的医疗急症；最重要的可逆干预是立即、快速的主动降温，不应因转运或其他检查而延误降温。',redFlags:['意识混乱/谵妄/昏迷','抽搐','核心体温显著升高','低血压或休克','横纹肌溶解/肝肾损伤/凝血异常'],steps:['立即移至凉爽环境，去除多余衣物，测核心体温并持续 ABC 监测。','热射病优先选择降温速度最快的主动降温方法，如冷水/冰水浸泡；不能浸泡时采用蒸发、传导等组合降温。','同时处理气道、抽搐、休克、电解质异常、低血糖、横纹肌溶解、肝肾损伤和凝血障碍。','不要等待到院后再降温；转运与快速降温应并行。'],caution:'普通退热药不能纠正热射病的病理性高热；若存在意识障碍，禁止口服补液。'},
    '溺水': {status:'verified',sourceIds:['rcukDrowning2025'],summary:'溺水复苏的核心是安全救援和尽早纠正低氧。无反应且无正常呼吸时，先给予 5 次通气，再继续标准 CPR。',redFlags:['无反应/无正常呼吸','持续低氧','低体温','疑似颈椎/严重创伤','复苏后呼吸衰竭'],steps:['救援者自身安全优先，尽可能使用浮具和受训的救援方式；不要让未受训者贸然下水。','离水后若无反应且无正常呼吸，先给予 5 次通气（有条件时使用高浓度氧），然后按标准 CPR 继续。','使用球囊面罩时避免过高通气压力，减少胃胀气和反流风险。','脊柱固定不应延误需要立即复苏者的离水和通气。','同时评估低体温并按低体温复苏原则处理；ROSC 后进入标准复苏后管理。'],caution:'不要常规进行腹部按压“排水”；复苏重点是通气、氧合与循环。'},
    '上消化道出血': {status:'verified',sourceIds:['acgUGIB2021'],summary:'显性上消化道出血首先评估循环与持续出血风险，尽早静脉通路、复苏和风险分层，并安排及时内镜止血。',redFlags:['低血压/休克','持续大量呕血或鲜红血便','晕厥/进行性意识改变','快速 Hb 下降','肝硬化/抗凝背景或严重合并症'],steps:['先复苏再内镜：建立静脉通路，交叉配血，动态监测生命体征、Hb、尿量和持续出血表现。','非常低危患者可用 Glasgow-Blatchford Score 辅助识别；ACG 提到 GBS 0–1 可考虑门诊管理，但必须结合临床判断。','住院 UGIB 患者一般采用限制性红细胞输血策略，ACG 建议 Hb 约 7 g/dL 作为常用输血阈值；心肌缺血等特殊情况需个体化。','住院患者建议在到诊后 24 小时内完成上消化道内镜；活动性溃疡出血或可见血管需内镜止血。','成功内镜止血后使用高剂量 PPI 3 天，随后前 2 周通常口服 PPI 每日 2 次；再出血先考虑再次内镜，内镜失败再转介栓塞/介入。'],caution:'肝硬化/疑似静脉曲张出血需要单独的门脉高压出血路径，不能完全套用非静脉曲张溃疡出血流程。'}
  });

  Object.assign(C.drugs, {
    '氯化钙': {status:'verified',sourceIds:['rcukElectrolyte2025'],indications:['重度高钾伴 ECG 改变','高钾性心搏骤停'],doses:['10% 氯化钙 10 mL IV，约 5 分钟给予；高钾性心搏骤停同剂量快速纳入 ALS。'],cautions:['仅稳定心肌膜，不降低总血钾；需同时降钾。','避免与碳酸氢钠在同一路径直接混合，必要时分开通路或充分冲管。']},
    '葡萄糖酸钙': {status:'verified',sourceIds:['rcukElectrolyte2025'],indications:['重度高钾伴 ECG 改变，氯化钙不可用时'],doses:['10% 葡萄糖酸钙 30 mL IV，约 10 分钟给予。'],cautions:['仅稳定心肌膜，不降低总血钾；治疗后需动态 ECG 和血钾复评。']},
    '普通胰岛素（高钾/DKA）': {status:'verified',sourceIds:['rcukElectrolyte2025','dka2024'],indications:['中重度高钾','成人 DKA/HHS 静脉胰岛素治疗'],doses:['高钾：短效/可溶性胰岛素 10 U + 葡萄糖 25 g IV。','DKA：固定速率 IV 0.1 U/kg/h；无酸中毒 HHS 常用 0.05 U/kg/h。'],cautions:['低钾时胰岛素可能诱发致命性心律失常；DKA/HHS 中 K<3.5 mmol/L 先补钾。','高钾治疗后必须严密监测低血糖。']}
  });
})();
