(() => {
  const C=window.CLINICAL_DATA;if(!C)return;
  Object.assign(C.sources,{
    ahaALS2025:{name:'2025 AHA Guidelines Part 9: Adult Advanced Life Support',year:'2025',org:'American Heart Association',url:'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-advanced-life-support',note:'Current AHA adult ALS recommendations for bradycardia, tachyarrhythmia, cardioversion and AF/flutter with rapid ventricular response.'},
    ahaAlgorithms2025:{name:'2025 AHA CPR/ECC Algorithms',year:'2025',org:'American Heart Association',url:'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/algorithms/',note:'Current accessible adult bradycardia, tachyarrhythmia and electrical cardioversion algorithms.'},
    ahaAF2023:{name:'2023 ACC/AHA/ACCP/HRS Guideline for Atrial Fibrillation',year:'2023',org:'ACC/AHA/ACCP/HRS',url:'https://professional.heart.org/en/science-news/2023-acc-aha-accp-hrs-guideline-for-the-diagnosis-and-management-of-atrial-fibrillation',note:'AF diagnosis, stroke-risk, anticoagulation and rhythm/rate management guideline; acute ALS details updated by AHA 2025.'}
  });
  Object.assign(C.topics,{
    '症状性心动过缓':{status:'verified',sourceIds:['ahaALS2025','ahaAlgorithms2025'],summary:'成人心动过缓是否需要急救，关键不是单看心率，而是判断低血压、急性意识改变、休克、缺血性胸部不适或急性心衰等低灌注表现，并同时寻找可逆病因。',redFlags:['低血压','急性意识改变','休克征象','缺血性胸部不适','急性心力衰竭','高度房室传导阻滞伴不稳定'],steps:['维持气道和呼吸，低氧时给氧；持续心电、血压、血氧监测并建立静脉通路。','同步寻找并处理缺氧、缺血/梗死、高钾、低体温、药物/毒物等可逆原因。','存在心肺灌注受损且心动过缓持续时给予阿托品；无效时尽快经皮起搏和/或多巴胺、肾上腺素持续输注。','顽固不稳定或高度房室传导阻滞应尽快专家会诊并准备经静脉临时起搏。'],doses:['阿托品 1 mg IV 推注，每 3–5 分钟可重复，最大总量 3 mg。','多巴胺持续静脉输注常用 5–20 μg/kg/min，按反应滴定。','肾上腺素持续静脉输注 2–10 μg/min，按反应滴定。'],caution:'阿托品用于有脉症状性心动过缓的剂量与有机磷/氨基甲酸酯中毒的“大剂量滴定至阿托品化”完全不同，严禁混用剂量逻辑。'},
    '规则窄QRS心动过速':{status:'verified',sourceIds:['ahaALS2025','ahaAlgorithms2025'],summary:'规则窄QRS心动过速先判断是否由心动过速本身造成血流动力学不稳定；稳定患者优先迷走神经刺激和腺苷，不稳定患者应同步电复律。',redFlags:['低血压','急性意识改变','休克','缺血性胸部不适','急性心衰'],steps:['气道、呼吸、监护、IV、12导联 ECG；低氧时给氧。','稳定且规则窄QRS：先迷走神经刺激；随后可使用腺苷。','若药物/迷走刺激无效或禁忌，可考虑同步电复律并请专科支持。','若存在持续性心动过速导致的不稳定，立即同步电复律；清醒患者在不延误治疗前提下尽可能镇静。'],doses:['腺苷首剂 6 mg 快速 IV 推注并立即生理盐水冲管；需要时第二剂 12 mg。','2025 AHA 电复律算法：规则窄QRS心动过速同步电复律初始 100 J。'],caution:'腺苷仅适合规则节律；哮喘患者存在严重支气管痉挛风险。中央静脉通路或心脏移植患者对腺苷可能异常敏感，需特别谨慎。'},
    '宽QRS心动过速（有脉）':{status:'verified',sourceIds:['ahaALS2025','ahaAlgorithms2025'],summary:'成人宽QRS心动过速首先按稳定性分层；不稳定单形性宽QRS心动过速优先同步电复律，多形性室速不能可靠同步，应按高能量非同步除颤处理。',redFlags:['低血压/休克','急性意识改变','缺血性胸痛','急性心衰','多形性室速','进行性恶化'],steps:['持续监护、IV、12导联 ECG，并评估 QRS≥0.12 s、节律规则性及是否单形。','不稳定宽QRS心动过速：立即同步电复律；多形性室速使用非同步高能量电击。','稳定规则单形宽QRS：可考虑腺苷作诊断/治疗，或胺碘酮/普鲁卡因胺/索他洛尔等抗心律失常治疗，并准备电复律。','积极寻找缺血、高钾、钠通道阻滞药物中毒、长QT/电解质异常等病因。'],doses:['稳定宽QRS心动过速：胺碘酮 150 mg IV 于 10 分钟内输注；室速复发可重复，随后 1 mg/min 维持 6 小时。','单形性室速同步电复律初始 100 J；多形性室速使用非同步高能量电击。'],caution:'血流动力学不稳定、节律不规则或多形性宽QRS心动过速不得使用腺苷。宽QRS心动过速禁用维拉帕米/地尔硫卓作为经验治疗。'},
    '房颤/房扑伴快速心室率':{status:'verified',sourceIds:['ahaALS2025','ahaAF2023'],summary:'房颤/房扑伴快速心室率先区分心律失常是否真正造成不稳定，并同时寻找感染、缺氧、ACS、心衰、电解质异常等触发因素。',redFlags:['因快速心室率导致的低血压/休克','进行性缺血','急性心衰','急性意识改变','预激房颤/房扑'],steps:['若不稳定明确由房颤/房扑快速心室率造成，立即同步电复律。','稳定且无预激：可按患者心功能、血压和合并症选择静脉 β受体阻滞剂或非二氢吡啶类钙拮抗剂控制心室率；危重患者可考虑 IV 胺碘酮。','同时评估发作持续时间、抗凝状态、卒中风险和出血风险；非紧急复律尤其需考虑血栓栓塞风险。','预激房颤/房扑不能按普通房颤使用房室结阻滞药；应优先专家支持/电复律。'],doses:['2025 AHA：房颤同步电复律初始至少 200 J（双相）；房扑可从 200 J 开始并根据设备/失败情况递增。','IV 地尔硫卓常用 0.25 mg/kg 于 2 分钟内推注，随后 5–10 mg/h；低血压、心衰/心肌病、ACS 等需避免或慎用。','IV 美托洛尔 2.5–5 mg 于 2 分钟内给药，最多 3 次；失代偿心衰避免。','危重且无预激时 IV 胺碘酮可用于心率控制；AHA 表列 300 mg/1 h，随后 10–50 mg/h/24 h，但具体方案需结合场景与本机构流程。'],caution:'预激房颤/房扑时，地高辛、非二氢吡啶钙拮抗剂、β受体阻滞剂和 IV 胺碘酮可能加速旁路传导并诱发 VF，应避免。'}
  });
  Object.assign(C.algorithms,{
    '成人有脉心动过缓':{status:'verified',sourceIds:['ahaAlgorithms2025'],points:['确认心动过缓与临床状态是否匹配，通常 HR<50/min。','判断低血压、意识改变、休克、缺血性胸痛、急性心衰。','有灌注受损：阿托品；无效则经皮起搏和/或多巴胺/肾上腺素输注。','同步处理缺氧、缺血、高钾、低体温、药物/毒物等可逆原因。','顽固不稳定：专家会诊并准备经静脉起搏。'],doses:['阿托品 1 mg IV，q3–5min，最大 3 mg。','多巴胺 5–20 μg/kg/min。','肾上腺素 2–10 μg/min。']},
    '成人有脉心动过速':{status:'verified',sourceIds:['ahaAlgorithms2025'],points:['气道/呼吸、监护、血压/血氧、IV、12导联 ECG。','判断心动过速是否导致低血压、意识改变、休克、缺血性胸痛或急性心衰。','不稳定：同步电复律；多形性室速非同步除颤。','稳定：先按 QRS 宽窄、规则性和节律类型选择迷走刺激、腺苷或抗心律失常治疗。','始终重新评估“心动过速是病因还是脓毒症/缺氧等病情的表现”。'],doses:['腺苷 6 mg 快速 IV；需要时 12 mg。','稳定宽QRS：胺碘酮 150 mg/10min，随后 1 mg/min×6h。']}
  });
  Object.assign(C.drugs,{
    '阿托品':{status:'verified',sourceIds:['ahaAlgorithms2025'],indications:['有脉症状性心动过缓伴心肺灌注受损'],doses:['1 mg IV 推注；每 3–5 分钟可重复；最大总量 3 mg。'],cautions:['与有机磷中毒的阿托品剂量逻辑不同。','治疗同时必须寻找低氧、缺血、高钾、药物等可逆病因。']},
    '胺碘酮':{status:'verified',sourceIds:['ahaALS2025','ahaAlgorithms2025'],indications:['稳定宽QRS心动过速/单形性室速等特定场景','部分危重无预激房颤/房扑快速心室率的心率控制'],doses:['稳定宽QRS心动过速：150 mg IV 于 10 分钟内；室速复发可重复，随后 1 mg/min 维持首 6 小时。'],cautions:['预激房颤/房扑时 IV 胺碘酮可能有害，应避免。','输注可引起低血压；与其他延长 QT/抗心律失常药联合需谨慎。']},
    '腺苷':{status:'verified',sourceIds:['ahaAlgorithms2025','ahaALS2025'],indications:['稳定规则窄QRS心动过速','稳定、规则、单形宽QRS心动过速时可作诊断/治疗'],doses:['6 mg 快速 IV 推注并立即 NS 冲管；需要时 12 mg。'],cautions:['不用于不稳定、节律不规则或多形性宽QRS心动过速。','哮喘患者可发生严重支气管痉挛。','中央静脉或心脏移植患者可能高度敏感。']}
  });
})();